package cwlexec

import (
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/yardrail/cwl-go/pkg/cwlcore"
)

// Collecting a CommandLineTool's outputs once the process it describes has exited.
//
// CommandLineTool.yml, CommandOutputBinding: "The output parameter value is generated by applying
// these operations in the following order: glob, loadContents, outputEval, secondaryFiles." The
// format of an output parameter is applied last of all, after the value it applies to is final,
// which is also where the reference implementation applies it.
//
// Nothing here runs a process, builds a command line or stages an input. It reads a directory the
// process has finished writing to and turns it into an output object.

// Errors reported while collecting outputs. They are wrapped with context, so callers should test
// them with [errors.Is].
var (
	// ErrOutputDir reports an output directory that is not an absolute path. Every File and
	// Directory value collected from it carries an absolute path and a file: IRI derived from
	// that path, neither of which a relative directory can produce.
	ErrOutputDir = errors.New("output directory must be an absolute path")

	// ErrOutputMissing reports a required File- or Directory-typed output whose glob matched
	// nothing. An optional one — a type union with a null member — is null instead.
	ErrOutputMissing = errors.New("output glob matched no files")

	// ErrOutputMultiple reports several matches for an output typed as a single File or
	// Directory. Silently keeping one of them would publish an arbitrary choice as though it
	// were the answer.
	ErrOutputMultiple = errors.New("output glob matched more than one path for a single value")

	// ErrStreamFile reports a stdout or stderr filename that is empty or that names a path
	// outside the output directory.
	ErrStreamFile = errors.New("captured stream filename is not a path inside the output directory")
)

// Stream identifies one of the two standard streams a CommandLineTool can capture to a file.
type Stream string

const (
	// StreamStdout is the tool's standard output, captured to the file CommandLineTool.stdout
	// names.
	StreamStdout Stream = "stdout"

	// StreamStderr is the tool's standard error, captured to the file CommandLineTool.stderr
	// names.
	StreamStderr Stream = "stderr"
)

// CollectOutputs gathers a CommandLineTool's declared outputs from outdir after the process has
// exited, and returns the output object keyed by output parameter short name; see [ShortName].
//
// outdir must be an absolute path, and is the directory the process was told to write to. exitCode
// is the status the process exited with, and is what an outputEval expression reads as
// runtime.exitCode — the one place the specification makes it available. inputs is the invocation's
// input object, eval the evaluator built for its requirement scope, and rt the runtime context the
// rest of its expressions are evaluated against; CollectOutputs sets rt.ExitCode itself for the
// outputEval evaluations and leaves it undefined everywhere else.
//
// Every declared output appears in the result, including one that collected nothing, whose value is
// a nil `any`. A downstream step wired to such a port sees null rather than blocking on a key that
// will never arrive.
//
// Values are typed: a File is a [*cwlcore.File] and a Directory a [*cwlcore.Directory], the same
// representation [LoadJobOrder] produces for an input object.
//
// CollectOutputs does not decide whether the process succeeded. [ClassifyExit] does, and the caller
// applies it: the specification makes the exit code available to outputEval precisely so that a
// tool may report a meaningful non-zero status and still describe its outputs, so collection cannot
// be conditional on the classification.
func CollectOutputs(tool *cwlcore.CommandLineTool, outdir string, exitCode int,
	inputs map[string]any, eval *cwlcore.Evaluator, rt cwlcore.RuntimeContext,
) (map[string]any, error) {
	if !filepath.IsAbs(outdir) {
		return nil, fmt.Errorf("%w: %q", ErrOutputDir, outdir)
	}

	collector := newOutputCollector(tool, outdir, inputs)
	collector.eval = eval
	collector.runtime = rt
	collector.exitCode = exitCode

	outputs := make(map[string]any, len(tool.Outputs))

	for index := range tool.Outputs {
		param := &tool.Outputs[index]
		name := ShortName(param.ID())

		value, err := collector.parameter(param)
		if err != nil {
			return nil, fmt.Errorf("collecting output %q: %w", name, err)
		}

		outputs[name] = value
	}

	return outputs, nil
}

// ClassifyExit maps a finished process's exit code to the status the tool declares for it.
//
// CommandLineTool.yml, successCodes: "Exit codes that indicate the process completed successfully.
// If not specified, only exit code 0 is considered success." temporaryFailCodes and
// permanentFailCodes name the two failure kinds, and anything a tool does not classify at all is a
// permanent failure — retrying a process that failed for a reason nobody described cannot be
// expected to help.
//
// A code named by more than one list is resolved in declaration order: success, then temporary,
// then permanent, matching the reference implementation. The document is contradicting itself in
// that case, and the order at least makes the contradiction resolve the same way every time.
//
// This lives beside output collection rather than inside it because the two answer different
// questions about the same finished process, and the stream that runs the process needs this one
// before it has an output directory worth reading.
func ClassifyExit(tool *cwlcore.CommandLineTool, exitCode int) Status {
	switch {
	case slices.Contains(tool.SuccessCodes, exitCode):
		return StatusSuccess
	case slices.Contains(tool.TemporaryFailCodes, exitCode):
		return StatusTemporaryFail
	case slices.Contains(tool.PermanentFailCodes, exitCode):
		return StatusPermanentFail
	case exitCode == 0:
		return StatusSuccess
	default:
		return StatusPermanentFail
	}
}

// StreamFile returns the file name a tool's captured standard stream is written to, relative to the
// output directory.
//
// It is the agreement between the stream that performs the redirection and this one, which has to
// glob for the same file afterwards. Both call this rather than one telling the other, so there is
// no ordering between them to get wrong.
//
// CommandLineTool.yml, stdout: "If there is no `stdout` name provided, a random filename will be
// created." What the name has to be is unique against the tool's own outputs, not unpredictable, so
// an undeclared stream gets a *derived* name — see [outGeneratedStreamFile] — which is reproducible
// and therefore agreeable to two callers that never speak.
//
// A declared name may be an expression, and is evaluated against inputs and rt. The result must be
// a relative path inside the output directory.
func StreamFile(tool *cwlcore.CommandLineTool, stream Stream, inputs map[string]any,
	eval *cwlcore.Evaluator, rt cwlcore.RuntimeContext,
) (string, error) {
	declared := tool.Stdout
	if stream == StreamStderr {
		declared = tool.Stderr
	}

	if declared == "" {
		return outGeneratedStreamFile(tool, stream), nil
	}

	name, err := eval.EvalString(string(declared),
		&cwlcore.EvalContext{Inputs: outExpressionObject(inputs), Runtime: rt})
	if err != nil {
		return "", err
	}

	err = outCheckStreamFile(stream, name)
	if err != nil {
		return "", err
	}

	return name, nil
}

// outCheckStreamFile rejects a captured-stream filename the engine cannot honour.
func outCheckStreamFile(stream Stream, name string) error {
	if name == "" {
		return fmt.Errorf("%w: %s names nothing", ErrStreamFile, stream)
	}

	if !filepath.IsLocal(name) {
		return fmt.Errorf("%w: %s names %q", ErrStreamFile, stream, name)
	}

	return nil
}

// outGeneratedStreamFile invents the filename for a captured stream the document did not name.
//
// It is the hex sha1 of the stream name and the tool's identifier. Deriving it rather than drawing
// it at random is what lets two independent callers agree on it, and the tool identifier is what
// keeps two tools in one workflow from colliding.
//
// The reference implementation does the same thing, hashing the tool document rather than its
// identifier, but reuses the one hash for both streams — so a tool that captures both and names
// neither redirects them to the same file. Seeding the hash with the stream name avoids that, and
// is the one deliberate deviation here.
func outGeneratedStreamFile(tool *cwlcore.CommandLineTool, stream Stream) string {
	return strings.TrimPrefix(outChecksumOf([]byte(string(stream)+"\x00"+tool.ID)), outChecksumPrefix)
}

// outputCollector carries the fixed context of one [CollectOutputs] call.
type outputCollector struct {
	// tool is the process whose outputs are being collected.
	tool *cwlcore.CommandLineTool

	// eval is the expression evaluator built for the invocation's requirement scope.
	eval *cwlcore.Evaluator

	// scope is the tool's own requirement scope, used to resolve a named output type against a
	// SchemaDefRequirement the tool declares itself; see [outputCollector.parameterTarget].
	scope *cwlcore.RequirementScope

	// inputs is the invocation's input object, already rendered in the shape an expression
	// reads; see [outExpressionObject].
	inputs map[string]any

	// roots are the paths the invocation's inputs occupy; see [outAllowedRoots].
	roots []string

	// runtime is the runtime.* context every expression but outputEval is evaluated against.
	runtime cwlcore.RuntimeContext

	// outdir is the cleaned absolute output directory.
	outdir string

	// outroot is outdir with its symlinks resolved, which is the form a resolved symlink target
	// has to be compared against; see [outputCollector.checkRetrievable].
	outroot string

	// exitCode is the status the process exited with, which only outputEval may read.
	exitCode int
}

// newOutputCollector settles everything the two ways a tool's outputs can arrive have in common:
// output binding, and a cwl.output.json the tool wrote for itself.
//
// Which paths a value may name is one of those things, and the reason this constructor exists rather
// than two struct literals. Both paths ask the same question — is this path inside the output
// directory, or one of the paths the invocation brought into it — and answering it from two
// independently-assembled root sets is how the two answers drift apart.
//
// outdir need not be clean; the collector's is.
func newOutputCollector(
	tool *cwlcore.CommandLineTool, outdir string, inputs map[string]any,
) *outputCollector {
	dir := filepath.Clean(outdir)
	rendered := outExpressionObject(inputs)
	scope := cwlcore.NewScope(tool)

	return &outputCollector{
		tool:    tool,
		scope:   scope,
		inputs:  rendered,
		roots:   outAllowedRoots(rendered, scope),
		outdir:  dir,
		outroot: outResolvePath(dir),
	}
}

// context builds the evaluation context for an expression outside outputEval, with self bound to
// the given value.
//
// runtime.exitCode is left undefined. CommandLineTool.yml offers it to outputEval and to nothing
// else, and cwlcore renders an undefined runtime field as absent, so a glob or secondaryFiles
// expression that reaches for it fails loudly instead of reading a plausible zero.
func (c *outputCollector) context(self any) *cwlcore.EvalContext {
	return &cwlcore.EvalContext{Inputs: c.inputs, Self: self, Runtime: c.runtime}
}

// outputEvalContext builds the evaluation context for an outputEval expression, which is the one
// place runtime.exitCode is defined.
func (c *outputCollector) outputEvalContext(self any) *cwlcore.EvalContext {
	runtime := c.runtime
	runtime.ExitCode = &c.exitCode

	return &cwlcore.EvalContext{Inputs: c.inputs, Self: self, Runtime: runtime}
}

// parameter collects one declared output parameter's value.
//
// A parameter whose type reaches a record is collected field by field, from the bindings the fields
// carry themselves — unless its own binding names an outputEval, which produces the whole record;
// see [outputCollector.record] and the rule at the head of clt_output_record.go. In the field-by-
// field case the parameter's own secondaryFiles and format are not applied either, because both
// decorate a File and a record is not one: a record's Files are its fields' values, and a field
// declares its own.
func (c *outputCollector) parameter(param *cwlcore.CommandOutputParameter) (any, error) {
	target := c.parameterTarget(param)

	shape := outRecordType(target.typ)
	if shape.schema != nil && !outEvaluatesWhole(target.binding) {
		return c.record(shape)
	}

	return c.bound(target)
}

// bound collects one declaration's value through the output binding it carries itself.
//
// It is the whole of an output binding — glob, loadContents, outputEval, secondaryFiles, format —
// applied to whichever declaration [outTarget] was projected from, so that a record field is
// collected by exactly the machinery a top-level parameter is.
func (c *outputCollector) bound(target *outTarget) (any, error) {
	binding, patterns, err := c.collectionPlan(target)
	if err != nil || binding == nil {
		return nil, err
	}

	globbed, err := c.globValues(patterns, binding)
	if err != nil {
		return nil, err
	}

	value, err := c.bindValue(target, binding, globbed, patterns)
	if err != nil {
		return nil, err
	}

	return value, c.publish(target, value)
}

// publish checks a collected value against the type it was declared as, decorates it, and completes
// the listing of every Directory it carries.
//
// The type check is what makes a glob answer the declaration it was written under. CommandLineTool.yml
// requires a glob to "match and return files/directories which actually exist" but says nothing about
// which of the two a pattern may match, so `*` under a `File[]` output will happily match a
// subdirectory; publishing it would put a Directory into a port declared to carry Files, and every
// consumer downstream would then be reading a value its own declaration says cannot be there. The
// check runs before secondaryFiles and format so that a mistyped value is reported as the type error
// it is, rather than as whatever the decorations make of it.
//
// Relocation runs after secondaryFiles, because a secondaryFiles expression is one of the two things
// that can leave a value declaring a name its path does not have; see [outputCollector.relocate].
//
// Nothing completes a Directory's listing here. What a tool's output binding says about `loadListing`
// governs what an outputEval sees and nothing more, so a Directory this tool did not read is left
// with the nil listing that means exactly that. Completing it is a *publication* concern and happens
// once, where the run's output object is assembled; see [outFillListings] for why the difference
// matters, and what goes wrong when a listing is frozen onto a value that is still in flight.
func (c *outputCollector) publish(target *outTarget, value any) error {
	err := checkValueType(cwlcore.ToExpressionValue(value), target.typ)
	if err != nil {
		return err
	}

	err = c.attachSecondaryFiles(target.secondaryFiles, value)
	if err != nil {
		return err
	}

	err = c.applyFormat(target.format, value)
	if err != nil {
		return err
	}

	return c.relocate(value)
}

// collectionPlan resolves what a declaration is collected through: the output binding that governs
// it, and the glob patterns to match. A nil binding means the declaration is not collected from the
// filesystem at all, and its value is null.
//
// The `stdout` and `stderr` type shortcuts stand in for a binding the document did not write.
// CommandLineTool.yml states the equivalence directly: an output of `type: stdout` is an output of
// `type: File` with `outputBinding: {glob: <the stdout file>}`. A shortcut that also carries an
// explicit binding keeps that binding's loadContents and outputEval but not its glob, which is the
// reference implementation's behaviour for a combination the specification forbids anyway.
func (c *outputCollector) collectionPlan(
	target *outTarget,
) (*cwlcore.CommandOutputBinding, []string, error) {
	stream, shortcut := outShortcutStream(target.typ)
	if !shortcut {
		if target.binding == nil {
			return nil, nil, nil
		}

		patterns, err := c.globPatterns(target.binding)

		return target.binding, patterns, err
	}

	name, err := StreamFile(c.tool, stream, c.inputs, c.eval, c.runtime)
	if err != nil {
		return nil, nil, err
	}

	binding := target.binding
	if binding == nil {
		binding = &cwlcore.CommandOutputBinding{}
	}

	return binding, []string{name}, nil
}

// outShortcutStream reports the standard stream a `stdout` or `stderr` typed output parameter
// captures, and whether the parameter uses one of the shortcuts at all.
func outShortcutStream(declared cwlcore.TypeRef) (Stream, bool) {
	switch declared.Kind() {
	case cwlcore.TypeKindStdout:
		return StreamStdout, true
	case cwlcore.TypeKindStderr:
		return StreamStderr, true
	default:
		return "", false
	}
}

// bindValue turns the globbed values into the parameter's value.
//
// outputEval replaces them outright — CommandLineTool.yml: "Evaluate an expression to generate the
// output value" — and self is bound to the array of matches whether there are none, one or many:
// "If no files were matched, `self` must be a zero length array; if a single file was matched, the
// value of `self` is an array of a single element". That holds whatever the glob found.
func (c *outputCollector) bindValue(target *outTarget,
	binding *cwlcore.CommandOutputBinding, globbed []cwlcore.FileOrDirectory, patterns []string,
) (any, error) {
	value := any(outWiden(globbed))

	if binding.OutputEval != "" {
		evaluated, err := c.evalOutput(binding.OutputEval, globbed)
		if err != nil {
			return nil, err
		}

		value = evaluated
	}

	return outReduceValue(target.typ, value, patterns)
}

// evalOutput evaluates an outputEval expression and re-types the File and Directory objects in
// whatever it produced.
func (c *outputCollector) evalOutput(
	expr cwlcore.Expression, globbed []cwlcore.FileOrDirectory,
) (any, error) {
	self := cwlcore.ToExpressionValue(globbed)

	evaluated, err := c.eval.Eval(string(expr), c.outputEvalContext(self))
	if err != nil {
		return nil, err
	}

	return c.retypeValue(evaluated)
}

// outReduceValue reduces a collected list to the single value a File- or Directory-typed
// declaration makes.
//
// A declaration typed as an array keeps the list, including an empty one — nothing matched is a
// perfectly good empty array. One typed as a single File is a different matter: no match is null if
// the type admits null and an error if it does not, and more than one match is always an error.
func outReduceValue(declared cwlcore.TypeRef, value any, patterns []string) (any, error) {
	items, ok := value.([]any)
	if !ok || !outSingleFileType(declared) {
		return value, nil
	}

	switch len(items) {
	case 0:
		return nil, outNoMatch(declared, patterns)
	case 1:
		return items[0], nil
	default:
		return nil, fmt.Errorf("%w: glob %s matched %d paths",
			ErrOutputMultiple, outQuoted(patterns), len(items))
	}
}

// outNoMatch reports a glob that matched nothing — unless the declared type admits null, in which
// case the output simply is null and there is nothing to report.
func outNoMatch(declared cwlcore.TypeRef, patterns []string) error {
	if declared.IsOptional() {
		return nil
	}

	return fmt.Errorf("%w: glob %s", ErrOutputMissing, outQuoted(patterns))
}

// outSingleFileType reports whether a declared type carries one File or Directory rather than a
// list of them. The stdout and stderr shortcuts are File by definition, and a union counts when any
// of its members does — which is what makes `File?` a single value.
func outSingleFileType(declared cwlcore.TypeRef) bool {
	switch declared.Kind() {
	case cwlcore.TypeKindStdout, cwlcore.TypeKindStderr:
		return true
	case cwlcore.TypeKindPrimitive:
		return declared.Name() == cwlcore.PrimitiveFile || declared.Name() == cwlcore.PrimitiveDirectory
	case cwlcore.TypeKindUnion:
		return slices.ContainsFunc(declared.Options(), outSingleFileType)
	default:
		return false
	}
}
