// Command gen-agents-md renders AGENTS.md from AGENTS.md.tmpl, filling in a
// package map scraped from the doc comments under cmd/ and pkg/, and a
// Taskfile target list scraped from Taskfile.yml.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

type moduleInfo struct {
	Path string `json:"Path"`
}

type goPackage struct {
	ImportPath string     `json:"ImportPath"`
	Doc        string     `json:"Doc"`
	Module     moduleInfo `json:"Module"`
}

type docPackage struct {
	ImportPath string
	Doc        string
}

type taskInfo struct {
	Name string
	Desc string
}

type taskLocation struct {
	Line int `json:"line"`
}

type taskListEntry struct {
	Name     string       `json:"name"`
	Desc     string       `json:"desc"`
	Location taskLocation `json:"location"`
}

type taskListResult struct {
	Tasks []taskListEntry `json:"tasks"`
}

type templateData struct {
	Packages []docPackage
	Tasks    []taskInfo
}

const (
	templateRelPath = "scripts/gen-agents-md/AGENTS.md.tmpl"

	outFileMode = 0o600

	generatedWarning = `<!--
This file is generated by scripts/gen-agents-md from ` + templateRelPath + `.
Edit that template, then run ` + "`task docs:agents`" + ` to regenerate this file.
Do not hand-edit AGENTS.md directly.
-->
`
)

func main() {
	err := run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-agents-md:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return fmt.Errorf("locating repo root: %w", err)
	}

	packages, err := listPackages(root)
	if err != nil {
		return fmt.Errorf("listing packages: %w", err)
	}

	tasks, err := listTasks(root)
	if err != nil {
		return fmt.Errorf("listing tasks: %w", err)
	}

	tmplPath := filepath.Join(root, templateRelPath)

	tmpl, err := template.ParseFiles(tmplPath)
	if err != nil {
		return fmt.Errorf("parsing %s: %w", tmplPath, err)
	}

	var out bytes.Buffer

	err = tmpl.Execute(&out, templateData{Packages: packages, Tasks: tasks})
	if err != nil {
		return fmt.Errorf("rendering template: %w", err)
	}

	outPath := filepath.Join(root, "AGENTS.md")

	err = os.WriteFile(outPath, withGeneratedWarning(out.Bytes()), outFileMode)
	if err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}

	return nil
}

// withGeneratedWarning inserts generatedWarning right after the rendered
// file's leading title line, so the warning lives only in the generated
// output rather than cluttering the template.
func withGeneratedWarning(rendered []byte) []byte {
	title, body, found := bytes.Cut(rendered, []byte("\n"))
	if !found {
		return rendered
	}

	const sep = "\n\n"

	out := make([]byte, 0, len(title)+len(sep)+len(generatedWarning)+len(body))
	out = append(out, title...)
	out = append(out, sep...)
	out = append(out, generatedWarning...)
	out = append(out, body...)

	return out
}

func repoRoot() (string, error) {
	out, err := exec.CommandContext(context.Background(), "go", "env", "GOMOD").Output()
	if err != nil {
		return "", err
	}

	return filepath.Dir(strings.TrimSpace(string(out))), nil
}

// listPackages scrapes package-level doc comments via `go list -json`,
// keeping only packages with a real doc comment.
func listPackages(root string) ([]docPackage, error) {
	cmd := exec.CommandContext(context.Background(), "go", "list", "-json", "./cmd/...", "./pkg/...")
	cmd.Dir = root

	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	var packages []docPackage

	decoder := json.NewDecoder(bytes.NewReader(out))
	for decoder.More() {
		var pkg goPackage

		err := decoder.Decode(&pkg)
		if err != nil {
			return nil, err
		}

		doc := strings.TrimSpace(pkg.Doc)
		if !strings.HasPrefix(doc, "Package ") && !strings.HasPrefix(doc, "Command ") {
			continue
		}

		importPath := strings.TrimPrefix(pkg.ImportPath, pkg.Module.Path+"/")
		packages = append(packages, docPackage{ImportPath: importPath, Doc: doc})
	}

	slices.SortFunc(packages, func(a, b docPackage) int {
		return strings.Compare(a.ImportPath, b.ImportPath)
	})

	return packages, nil
}

// listTasks scrapes task names and descriptions via `task --list-all --json`,
// restoring Taskfile declaration order (the command's own list order doesn't
// match the file) by sorting on each task's source line.
func listTasks(root string) ([]taskInfo, error) {
	cmd := exec.CommandContext(context.Background(), "task", "--list-all", "--json")
	cmd.Dir = root

	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	var result taskListResult

	err = json.Unmarshal(out, &result)
	if err != nil {
		return nil, err
	}

	slices.SortFunc(result.Tasks, func(a, b taskListEntry) int {
		return a.Location.Line - b.Location.Line
	})

	tasks := make([]taskInfo, len(result.Tasks))
	for i, t := range result.Tasks {
		tasks[i] = taskInfo{Name: t.Name, Desc: t.Desc}
	}

	return tasks, nil
}
